from config import db

class Stock(db.Model):
    __tablename__ = 'stocks'

    id = db.Column(db.Integer, primary_key=True)
    companyid = db.Column(db.String(80))
    companyname = db.Column(db.String(255))
    ticker = db.Column(db.String(10))
    price = db.Column(db.Float)
    p_l = db.Column(db.Float)
    dy = db.Column(db.Float)
    p_vp = db.Column(db.Float)
    p_ebit = db.Column(db.Float)
    p_ativo = db.Column(db.Float)
    ev_ebit = db.Column(db.Float)
    margembruta = db.Column(db.Float)
    margemebit = db.Column(db.Float)
    margemliquida = db.Column(db.Float)
    p_sr = db.Column(db.Float)
    p_capitalgiro = db.Column(db.Float)
    p_ativocirculante = db.Column(db.Float)
    giroativos = db.Column(db.Float)
    roe = db.Column(db.Float)
    roa = db.Column(db.Float)
    roic = db.Column(db.Float)
    dividaliquidapatrimonioliquido = db.Column(db.Float)
    dividaliquidaebit = db.Column(db.Float)
    pl_ativo = db.Column(db.Float)
    passivo_ativo = db.Column(db.Float)
    liquidezcorrente = db.Column(db.Float)
    peg_ratio = db.Column(db.Float)
    receitas_cagr5 = db.Column(db.Float)
    vpa = db.Column(db.Float)
    lpa = db.Column(db.Float)
    valormercado = db.Column(db.Float)
    segmentid = db.Column(db.Integer)
    sectorid = db.Column(db.Integer)
    subsectorid = db.Column(db.Integer)
    subsectorname = db.Column(db.String(255))
    segmentname = db.Column(db.String(255))
    sectorname = db.Column(db.String(255))

    def __init__(self, data):
        self.companyid = data.get('companyid')
        self.companyname = data.get('companyname')
        self.ticker = data.get('ticker')
        self.price = data.get('price')
        self.p_l = data.get('p_l')
        self.p_vp = data.get('p_vp')
        self.p_ebit = data.get('p_ebit')
        self.p_ativo = data.get('p_ativo')
        self.ev_ebit = data.get('ev_ebit')
        self.margembruta = data.get('margembruta')
        self.margemebit = data.get('margemebit')
        self.margemliquida = data.get('margemliquida')
        self.p_sr = data.get('p_sr')
        self.p_capitalgiro = data.get('p_capitalgiro')
        self.p_ativocirculante = data.get('p_ativocirculante')
        self.giroativos = data.get('giroativos')
        self.roe = data.get('roe')
        self.roa = data.get('roa')
        self.roic = data.get('roic')
        self.dividaliquidapatrimonioliquido = data.get('dividaliquidapatrimonioliquido')
        self.dividaliquidaebit = data.get('dividaliquidaebit')
        self.pl_ativo = data.get('pl_ativo')
        self.passivo_ativo = data.get('passivo_ativo')
        self.liquidezcorrente = data.get('liquidezcorrente')
        self.peg_ratio = data.get('peg_ratio')
        self.receitas_cagr5 = data.get('receitas_cagr5')
        self.vpa = data.get('vpa')
        self.lpa = data.get('lpa')
        self.valormercado = data.get('valormercado')
        self.segmentid = data.get('segmentid')
        self.sectorid = data.get('sectorid')
        self.subsectorid = data.get('subsectorid')
        self.subsectorname = data.get('subsectorname')
        self.segmentname = data.get('segmentname')
        self.sectorname = data.get('sectorname')

    def __repr__(self):
        return f"<Stock(companyname={self.companyname}, ticker={self.ticker}, price={self.price})>"
